version: "3"

services: 
  redis-master:
    image: redis:5
    ports: 
      - 6380:6379
    container_name: redis-master
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./conf/redis-master:/usr/local/etc/redis/
      - ./data/redis-master:/usr/local/redis/data
      - ./log/redis-master:/var/log/redis
    networks: 
      redis-net:
        ipv4_address: 10.10.20.101
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  redis-slave-01:
    image: redis:5
    ports: 
      - 6381:6379
    container_name: redis-slave-01
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./conf/redis-slave-01:/usr/local/etc/redis/
      - ./data/redis-slave-01:/usr/local/redis/data
      - ./log/redis-slave-01:/var/log/redis
    networks: 
      redis-net:
        ipv4_address: 10.10.20.102
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  redis-slave-02:
    image: redis:5
    ports: 
      - 6382:6379
    container_name: redis-slave-02
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./conf/redis-slave-02:/usr/local/etc/redis/
      - ./data/redis-slave-02:/usr/local/redis/data
      - ./log/redis-slave-02:/var/log/redis
    networks: 
      redis-net:
        ipv4_address: 10.10.20.103
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  redis-sentinel-01:
    image: redis
    ports:
      - 26380:26379
    container_name: redis-sentinel-01
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./conf/redis-sentinel-01:/usr/local/etc/redis/
      - ./log/redis-sentinel-01:/var/log/redis
    networks: 
      redis-net:
        ipv4_address: 10.10.20.104

    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
  
  redis-sentinel-02:
    image: redis
    ports:
      - 26381:26379
    container_name: redis-sentinel-02
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./conf/redis-sentinel-02:/usr/local/etc/redis/
      - ./log/redis-sentinel-02:/var/log/redis
    networks: 
      redis-net:
        ipv4_address: 10.10.20.105
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    tty: true
  
  redis-sentinel-03:
    image: redis
    ports:
      - 26382:26379
    container_name: redis-sentinel-03
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./conf/redis-sentinel-03:/usr/local/etc/redis/
      - ./log/redis-sentinel-03:/var/log/redis
    networks: 
      redis-net:
        ipv4_address: 10.10.20.106
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always

networks:
  redis-net:
    ipam:
      config:
      - subnet: 10.10.20.0/24
